#!/bin/bash

function check_env_dir() {
    local name_env_dir=$1
    if [ -z ${!name_env_dir} ]
    then
	echo "Environment variable $name_env_dir has not been set"
	exit 1
    fi

    if [ ! -d ${!name_env_dir} ]
    then
	echo "Environment variable $name_env_dir does not represent a directory"
	exit 1
    fi
}

check_env_dir COMMON_SOURCE_IDENTIFICATION_CASHMERE_DIR
BIN_DIR=$COMMON_SOURCE_IDENTIFICATION_CASHMERE_DIR/bin
source $BIN_DIR/check_environment_variable.bash

check_env CASHMERE_PORT

extra_args=( )
if echo "$@" | grep -q -- "-cpu"
then
    extra_args+=("-Dcashmere.nLocalExecutors=16")
    extra_args+=("-Xmx50G")
elif echo "$@" | grep -q -- "-mc"
then
    extra_args+=("-Dcashmere.nLocalExecutors=4")
    extra_args+=("-Xmx5G")
elif echo "$a" | grep -q -- "-use_cache"
then
    extra_args+=("-Dcashmere.nLocalExecutors=4")
    extra_args+=("-Xmx5G")
else
    echo "Need parameter -cpu, -mc, or -use_cache"
    exit 1
fi


ruby $BIN_DIR/run-on-nodes.das5.rb \
     $COMMON_SOURCE_IDENTIFICATION_CASHMERE_DIR \
     lib/common-source-identification-cashmere.jar \
     "${extra_args[@]}" \
     nl.junglecomputing.common_source_identification.CommonSourceIdentification \
     "$@"
